import = ["~/.CAR-configs/theme/active-palette.toml"]

[window]
opacity = 0.95
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11

[colors.primary]
background = "$base.bg"
foreground = "$base.fg"

[colors.cursor]
text   = "$base.bg"
cursor = "$accent.primary"

[colors.normal]
black   = "$surface.s0"
red     = "$state.error"
green   = "$state.success"
yellow  = "$state.warning"
blue    = "$accent.secondary"
magenta = "$accent.primary"
cyan    = "$accent.tertiary"
white   = "$base.fg"

[colors.bright]
black   = "$surface.s1"
white   = "$surface.s2"
