#defult apps
$terminal = alacritty
$fileManager = nautilus
$menu = wofi --show drun
$bar = waybar 
$bgManager = hyprpaper

#source modules
source = ~/.config/hypr/config/appearance/*
source = ~/.config/hypr/config/hardware/*
source = ~/.config/hypr/config/set-up/*
source = ~/.config/hypr/config/software/*

#layout
general {
	layout = master
}
