# Base
$bg            = rgb(1B0126)
$fg            = rgb(E9DFF2)

# Surfaces
$surface0      = rgb(241033)
$surface1      = rbg(472466) 

# State
$inactive      = rgb(7D6A9C)

# Accents
$primary       = rgb(CE84FD)
$secondary     = rgb(9A84B8)
$tertiary      = rgb(E8A2D5)

# Semantic
$error         = rgb(C94A4A)
$warning       = rgb(E0A43A)
$info          = rgb(7D48B4)
$addition      = rgb(7FB448)
