decoration {
	#window rounding
	rounding = 10
	rounding_power = 2

	#opacity
	active_opacity = 1.0
	inactive_opacity = 0.9
	
	#shadows
	shadow {
		range = 4
		render_power = 3
		color = rgba(00000000)
	}
	blur {
		enabled = true
		size = 3
		passes = 1
		vibrancy = 0.15
	}
}
