general {
    gaps_in = 3
    gaps_out = 5

    # borders
    border_size = 2
	col.active_border = rgba(2F1842DD)
	col.inactive_border = rgba(2F1842DD)

	resize_on_border = false

    # tearing
    allow_tearing = false
}

