general {
	gaps_in = 5
	gaps_out = 20
	
	#boarders
	boarder_size = 2
	col.active_boarder = rgba(00000000) rgba(FFFFFFFF) 45deg
	resize_on_boarder = false

	#tearing
	allow_tearing = false

	#layout
	layout = dwindle
}
